### PR TITLE
bugfix(utils): recalculates positioning toolbar - Iss #251 and #239

### PR DESCRIPTION
**Pull request by LuAnderson**
Add method to recalculates positioning when near edge to…

### CODE REVIEW

**Comment by icaromh** [comment]
@LuAnderson, 

When we select just the first word on the left this is happening. 

image

Also, the toolbar content it's dynamic so the width can vary.

**Comment by icaromh** [comment]
Hey @LuAnderson 🤗 

Were you able to reproduce this behavior?

**Comment by LuAnderson** [comment]
Yes... thanks for explaining, i will try to solve this bug

**Comment by icaromh** [comment]
> Yes... thanks for explaining, I will try to solve this bug

Great! If you need any help, we are here 😄

**Comment by mogavin** [comment]
Hi, @LuAnderson ! PR #291 addresses this issue, so we will close this PR. However, if you believe you can contribute to this issue, please let us know by opening a new PR. Thanks !

**Pull request closed without merging**
