### PR TITLE
Added: mutability parameter to setEntity()

### PR DESCRIPTION
**Pull request by leanazulyoro**
Allow entityInputs to pass a "mutability" value to the setEntity() method.

### CODE REVIEW

**Comment by leanazulyoro** [comment]
@vierno Sure, there you go, I just commited the change requested

**Comment by leanazulyoro** [comment]
@vierno any idea why a test is failing here? it doesn't happen in my local developing enviroment.

**Comment by marcelometal** [comment]
Hi @leanazulyoro, I ran your branch in my local developing environment and it fails =/

**Comment by leanazulyoro** [comment]
@marcelometal I just reverted my changes to be the save as my first commit, which passed the tests before, and now it does not pass them. Also, I still can't reproduce it in my local enviroment.

The test that fails doesn't look like it has anything to do with my changes.
I'm running "npm run test", I have npm v4.0.3, and node v4.4.7.

**Comment by leanazulyoro** [comment]
@marcelometal I updated my node and npm versions to match the ones travis CI uses, and efectively yes, the test fails, but it even fails in the master branch.

**Comment by marcelometal** [comment]
Hi @leanazulyoro, Could you please rebase on top of master?

We are pinning NodeJS to 7.2, because 7.3 breaks Megadraft's tests =/

**Comment by leanazulyoro** [comment]
@marcelometal done! :smile: thanks

**Comment by marcelometal** [comment]
@leanazulyoro  Thanks for contributing to Megadraft!

**Pull request merged**
