### PR TITLE
#247 - Incluir o aviso UNSAFE_ nos métodos marcados como depreciados

### PR DESCRIPTION
**Pull request by edgarberlinck**

### CODE REVIEW

**Comment by edgarberlinck** [comment]
fix for issue #247

**Comment by edgarberlinck** [comment]
@allanassis veja se está ok

**Comment by allanassis** [comment]
Like @marcelometal said, it is better to refactor then just saying which method is unsafe.

**Comment by edgarberlinck** [comment]
Ok, I’ll do it

Em sáb, 5 de out de 2019 às 00:59, Allan Assis <notifications@github.com>
escreveu:

**Comment by edgarberlinck** [comment]
Done @marcelometal.

**Comment by edgarberlinck** [comment]
@marcelometal I can take a look at those tests, but they aren't appear to be related to my code. Is that rigth?

**Comment by edgarberlinck** [comment]
@marcelometal Finally I get this thing done. Could you check please?

**Comment by icaromh** [comment]
@edgarberlinck, thanks for your contribution!

Seems that this code isn't working as expected: 

https://github.com/globocom/megadraft/pull/250/files#diff-e007c62f341ba9b8108617f3d82d21c8R160-R177

output

**Comment by edgarberlinck** [comment]
Thanks for the feedback. Could you give me more details? I couldn't understand exactly what should be fixed.

> @edgarberlinck, thanks for your contribution!
> 
> Seems that this code isn't working as expected:
> 
> https://github.com/globocom/megadraft/pull/250/files#diff-e007c62f341ba9b8108617f3d82d21c8R160-R177
> 
> output

**Comment by icaromh** [comment]
Sure! Sorry about that! 

The Toolbar should be positioned right in the middle of the selected text. As you can see in the following gif (it can be reproduced in [the website](http://megadraft.io/) by selecting some text).

expected

Probably it's something inside the [`getDerivedStateFromProps` function](https://github.com/globocom/megadraft/pull/250/files#diff-e007c62f341ba9b8108617f3d82d21c8R160-R177)

**Pull request closed without merging**
