### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by Aditya-Kapadiya**
Hello,
This file had some links with "HTTP" and I have changed it to "HTTPS"

Thank you.

### CODE REVIEW

**Review by lucianapepelucio — COMMENTED** [review]
Ok

**Comment by Aditya-Kapadiya** [comment]
@siqueira-ec I closed the #401 pull request. Sorry, for the mistake.

**Comment by Aditya-Kapadiya** [comment]
@lucianapepelucio Is this PR accepted as valid PR?

**Comment by Aditya-Kapadiya** [comment]
@lucianapepelucio On my hacktoberfest globocom profile It shows that I will receive a t-shirt. How can I claim it? I didn't received any email to claim it.

**Pull request merged**
