### PR TITLE
Mispositioning toolbar

### PR DESCRIPTION
**Pull request by wdtamagi**
fix for #291 

This PR fix toolbar position for highest left and right.

### CODE REVIEW

**Comment by wdtamagi** [comment]
I don't understand the issues of Codacy...

**Comment by wdtamagi** [comment]
The Codacy rule is without semi and the eslint.prettier/prettier rule is with semi...

**Comment by wdtamagi** [comment]
@mogavin Sure i will work on this fix, thanks for your reply.
And about Codacy issues?

**Comment by mogavin** [comment]
Thanks, @wdtamagi ! We will also check Codacy issues

**Comment by wdtamagi** [comment]
@mogavin Can you check again?

**Comment by wdtamagi** [comment]
Ops, sorry about that.
I will work on this.
Thanks @mogavin

**Comment by mogavin** [comment]
@wdtamagi, Codacy is ok now 👍

**Comment by wdtamagi** [comment]
@mogavin 
I fixed the test, but I don't understand the method "replaceSelection" not really replace the mocked selection...

**Comment by mogavin** [comment]
Thanks, @wdtamagi. As for replaceSelection method, I didn't understand your question. Could you detail it better?

**Comment by wdtamagi** [comment]
In the toolbar test have a method:
`const replaceSelection = (newSelection, wrapper) => {
  const selectionState = SelectionState.createEmpty("ag6qs");
  const updatedSelection = selectionState.merge(newSelection);
  const oldState = wrapper.state("editorState");

  const editorState = EditorState.forceSelection(oldState, updatedSelection);

  wrapper.setState({ editorState: editorState });
};`
This method mock the editorState of component, but all the math for calculate the position of toolbar use de DOM elements (src/utils.js method getSelectionCoords).

I believe for a really useful test of positioning of toolbar need mock the DOM position of editor for make thinks happen.

I can try do this on this PR or in another one.

**Comment by mogavin** [comment]
@wdtamagi 
I believe the objective of method `replaceSelection` is to change the **selectionState** portion of editorState, which influences the return of method `getVisibleSelectionRect` ([used in getSelectionCoords](https://github.com/globocom/megadraft/blob/0816ff44218bf945cf5d8ed6fe790bd52fc79e5a/src/utils.js#L54)). But any suggestions for improvement will be very welcome, thanks for your contribution!

**Comment by KyleLawson16** [comment]
This seems to have stopped the toolbar from going out of view of the window, however now I'm seeing an issue with positioning of the toolbar with selected text on the left side of the editor. Running v0.7.0

megadraft-toolbar

**Comment by mogavin** [comment]
Hi @KyleLawson16 ! Yep, we have become aware of this problem recently. We will soon work on a correction ( but, as always, we are open to contributions too 😀 ). Thanks !

**Comment by KyleLawson16** [comment]
Hey @mogavin I was able to find some time to tackle it #310

**Comment by mogavin** [comment]
Great, @KyleLawson16! We will review this PR and provide feedback soon. Thanks !

**Pull request merged**
