### PR TITLE
Adds optional prop to allow change of readOnly

### PR DESCRIPTION
**Pull request by mameneses**

### CODE REVIEW

**Comment by marcelometal** [comment]
Hi @mameneses,
Thanks for contributing to Megadraft!

Just to make it clear, what is the use case for this change?

**Comment by mameneses** [comment]
Hola @marcelometal,
Megadraft is a great! I am happy to try help out.

The use case would be to allow for permission structures. For example, in my case, if a user only has permission to read and not permission to write to a shared document, exposing the readOnly prop would allow for an easy implementation of that users authorization.

**Comment by marcelometal** [comment]
Hi @mameneses ,
Could you please squash your commits together so we get a clean, reversible git history?

**Comment by marcelometal** [comment]
Done! Thank you!

**Comment by mameneses** [comment]
Thanks!

**Pull request merged**
