### PR TITLE
Fix toolbar and refactor positioning

### LINKED ISSUE #193: Toolbar vertical positioning
When using megadraft in a limited height window (Example, IFrame), the editor will often find itself with the first line being to far up to display the toolbar.

For example, this would happen if you scrolled too far up in megadraft.io

2018-02-20 11_40_06-megadraft - draft js rich text editor

However, the expected behavior would be something akin to this : 

2018-02-20 11_39_41-megadraft - draft js rich text editor

I am implementing megadraft into my application and I already had to create a fork to fix some issues with iframes, as such, I used this fork to try and build a fix for this issue as well. You can find it in these two files.

https://github.com/Minivera/megadraft/blob/master/src/components/Toolbar.js
https://github.com/Minivera/megadraft/blob/master/src/utils.js

The second screenshot taken above is taken from my fork. 

I also used this chance to fix both #143 and #190 as well, though my solution may not be the best for both. Unfortunately, my fixes also broke one of the unit tests for the toolbar which checks for an offset of 14px for the toolbar, as the toolbar would instead fix itself under the selection in the test case.

Considering this, I though I'd first create an issue to check and discuss a possible solution before going for a PR.

### PR DESCRIPTION
**Pull request by Minivera**
This pull request was created after a discussion in issue #193.

Its goal is to fix #193, #190 and #143.

### CODE REVIEW

**Comment by Minivera** [comment]
I will fix the linting errors quickly, I believe the test is failing due to the code not changing the style on the DOM node directly anymore.

**Comment by marcelometal** [comment]
HI Minivera , could you please fix the tests?

**Comment by Minivera** [comment]
Oh sure, I though you might have wanted to fix them yourselves. I'll fix them right now, sorry about that.

**Comment by vierno** [comment]
Sorry for the long delay, @Minivera I'm integrating the code on the master branch. Thanks!

**Comment by macrozone** [comment]
this PR breaks https://github.com/globocom/megadraft/pull/192 and basically it breaks shouldDisplayToolbarFn completly, because you don't retrieve any arguments anymore



sorry, i haven't been around here for a while and i am late with the review.

I will open up a new issue

**Pull request merged**
