### PR TITLE
Selection state on image block (close #27)

### LINKED ISSUE #27: Selection state on media block
Add visual feedback to media block selection.

screen shot 2016-04-27 at 5 14 29 pm

### PR DESCRIPTION
**Pull request by wdtamagi**
Related Issue #27 

Apply style by selection state to the image block.

imageblock

Used selected react state on ImageBlock component and forward event handlers and properties until BlockWrapper for handle with select state and style.

### CODE REVIEW

**Comment by Chavao** [comment]
Hey @wdtamagi, thanks for your PR.

When you select the box the element moves inside. Could you please try to fix this behaviour and add some tests to assert this state?

**Comment by wdtamagi** [comment]
Hello @Chavao ,

Thanks for your reply,
off course I will work on this ;)

**Comment by wdtamagi** [comment]
@Chavao ,
 
I added a new test for cover the selection state when focus and blur of the element.

What you mean when you say about the behavior of the component, the blue border need stay on the hovered image component wrapper?
Because today the blue border is on the image component.

I don't know if I understood correctly.

**Comment by Chavao** [comment]
@wdtamagi thanks for add the tests.

Your implementation of the blue border is in the right place, but the problem is when you click in the block, all contents inside resizes to fit in the new border space, so the feeling is having a weird movement of all internal components.

I think if you change the `border` to `outline` will fix this behavior.

Could you fix it?

**Comment by wdtamagi** [comment]
@Chavao you have eagle eyes man! kk
Sorry for not understand you on first comment.
I have added a new style using outline with auto style for rounded corners.

**Comment by mogavin** [comment]
Hi @wdtamagi ! We re-analyzed this issue and, because we have change plans that will affect both the visual and structural aspects, we believe it would not fit right now. Anyway we appreciate your contribution and we ask you to follow our future roadmaps.

**Comment by wdtamagi** [comment]
No problem @mogavin, thanks for your reply.

**Pull request closed without merging**
