### PR TITLE
Avoid preventDefault int Toolbar for select input

### PR DESCRIPTION
**Pull request by dimooze**
Hello, 
I had an issue when creating an Entity input with a select input inside, with the preventDefault from onMouseDown inside Toolbar, the select input won't open.
Tell me if everything is ok for you :)

### CODE REVIEW

**Comment by nihaux** [comment]
Bump, would be cool if you could review this ! thx :)

**Comment by icaromh** [comment]
Thanks for your contribution, we'll take a look 🤗

**Comment by Chavao** [comment]
Hey @dimooze!

Can you please add some tests? Thanks!

**Comment by Annatsu** [comment]
I have created a PR on #305 adding an integration test for it. Hoping to get this merged soon! Thanks :)

**Comment by mogavin** [comment]
Replaced by PR #305

**Pull request closed without merging**
