### PR TITLE
Feature/toolbar outside window

### PR DESCRIPTION
**Pull request by huitre**
This pull request fix the problem of the toolbar displaying sometimes outside of the window. It automatically adapt it position, and the little selection arrow, so it force it to stay in the innerwidth of the window. 

I hope this help some people :)

### CODE REVIEW

**Comment by stev3reed** [comment]
Awesome @huitre! If this solution works can we merge that jazz?

**Comment by huitre** [comment]
Yep, @stev3reed, you can checkout this branch if you want to check, and then merge it.

**Comment by vierno** [comment]
Hello @huitre , thanks again! I released it: 0.4.24

**Comment by huitre** [comment]
thank you @vierno!

**Pull request merged**
